### ISSUE TITLE
results reported in the paper

### ISSUE THREAD

**Issue by firasl** [alanjeffares/TANGOS#2]
Hi, 
Thanks for making the codes available. 
How to interpret the results in the json files to match the results reported in the paper?

**Comment by alanjeffares** [comment]
Hi @firasl ,

Thanks for your interest in our work! 

After running an experiment (e.g. `python src/experiments/stand-alone-regularization/main.py`) the corresponding results will be saved in the results folder (e.g. `src/experiments/stand-alone-regularization/results`) in json format for each seed. After loading, the results can then be accessed by something like `results_dict[<dataset>][<regularizer>][<run>]` which contains validation and test performance. The results should be identical to those in the paper although there might be some exceptions due to a new more efficient implementation of TANGOS (if I remember correctly this is the case for dropout) which we have provided more details about [here](https://github.com/alanjeffares/TANGOS/blob/main/src/legacy/comment.md). 

Note that if you wish to simply get up and started with running TANGOS and don't need the full infrastructure of the codebase we have also provided a [getting started notebook](https://github.com/alanjeffares/TANGOS/blob/main/TANGOS_quickstart.ipynb).

**Comment by firasl** [comment]
thanks for your answer @alanjeffares. I managed to produce (almost) most of the results reported in the paper. 
Thanks again for the codes.  This is an exciting approach to boost the performance of NN. In my perspective, it is quite similar in principle to this work in [AAAI-23]( https://arxiv.org/pdf/2301.01352.pdf) and this work [ICLR-16](https://arxiv.org/pdf/1511.06068.pdf) However, these two papers considers the similarity between neuron outputs directly and not attributes (gradients) like in this work. 
Interestingly, when considering the diversity of the output directly, dropout encourages diversity and reduces correlation, as shown [here](https://arxiv.org/pdf/1511.06068.pdf). Unlike, when considering neurons' attributes, it yields more correlated attributes like you observed in your paper.

**Comment by alanjeffares** [comment]
Happy to help @firasl! 

Yes exactly. The distinction is subtle but, as you point out, inducing behavior in neurons vs neuron attributions can result in very different characteristics in the resulting networks. I think there are some exciting research directions to really take these ideas to the next level. Thanks for sharing your paper, really interesting and will be great to be aware of in my future work.
